version: 2
builds:
  - id: hx-secrets-akv-arm64
    binary: hx-secrets-akv
    goos:
      - linux
    goarch:
      - amd64
    main: ./main.go
    hooks:
      pre: go mod tidy
      post: go mod tidy
    env:
      - CGO_ENABLED=1