version: 2
builds:
  - id: hx-secrets-akv-darwin
    binary: hx-secrets-akv
    goos:
      - darwin
    goarch:
      - arm64
    main: ./main.go
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++